input {
  gelf {
    port => 12201
    type => "docker-gelf"
  }
}

filter {
  if [type] == "docker-gelf" {
    
    if ([service] == "nginx-traffic" or  [container_name] == "tradehub-backend" or [tag] == "nginx-proxy") and [message] =~ /^\{/ {
      json {
        source => "message"
      }
      
      if !("_jsonparsefailure" in [tags]) {
        mutate {
          remove_field => [ "message" ]
        }
      }
    }

    if [container_name] == "tradehub-backend" {
      mutate {
        gsub => [ "message", "\x1B\[[0-9;]*[a-zA-Z]", "" ]
      }
    }

    if [service] == "nginx-traffic" {
      mutate { 
        add_field => { "[@metadata][target_index]" => "tradehub-traffic" } 
      }
    } else {
      mutate { 
        add_field => { "[@metadata][target_index]" => "tradehub-status" } 
      }
    }
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "%{[@metadata][target_index]}-%{+YYYY.MM.dd}"
  }
  stdout { codec => rubydebug }
}